import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={"h-screen bg-black"}>
				<p className={"text-4xl text-center text-red-500"}> Hello World </p>
			</main>
		</>
  )
}
