import Head from 'next/head'
import Image from 'next/image'

import Layout from '../components/layout'
import Landing from '@/components/landing/landing'
import Intergration from '@/components/integration/integration'
import About from '@/components/about/About'

export default function Home() {
  return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Layout>
					<Landing />
					<Intergration />
					{/* <About /> */}
				</Layout>
			</main>
		</>
  )
}
